name: Deploy Microsite

on:
  push:
    branches:
      - trunk
    paths:
      - '.github/workflows/deploy-microsite.yml'
      - 'microsite/**'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy-microsite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Microsite yarn install
        run: yarn
        working-directory: microsite

      - name: Build microsite
        run: yarn docusaurus build
        working-directory: microsite

      - name: Deploy microsite
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: microsite/build
